#ifndef FILELOGGER_H
#define FILELOGGER_H
#include <stddef.h>
#define FILELOGGER_DEFAULT_MAX_LINE 512
#define FILELOGGER_DEFAULT_MAX_FILESS 10
#define FILELOGGER_DEFAULT_MAX_BYTES_SIZE (10 * 1024 * 1024)
#define FILELOGGER_DEFAULT_BUFFER_SIZE 4096
#define FILELOGGER_TS_FORMAT "%Y%m%d%H%M%S"
#define FILELOGGER_FILE_SUFFIX_LEN 4







#endif /** !FILELOGGER_H **/